#!/usr/bin/env bash
# install-system.sh — system-wide install / uninstall for Lattice.
#
# One centralized, distro-neutral install path for Ubuntu, Arch, and Fedora.
# It installs ONLY files that Lattice ships and, on uninstall, removes ONLY
# those same files. It never installs packages, never touches user data
# (~/.config, ~/.local/share, ~/.cache), and never changes your default file
# manager. Setting Lattice as the default folder opener is a separate, explicit
# step documented in the README (`xdg-mime default …`).
#
# Usage (run from anywhere; the source tree is resolved from this script):
#
#   cargo build --release           # build first — a release binary is required
#   sudo ./scripts/install-system.sh
#   sudo ./scripts/install-system.sh --uninstall
#
# Options:
#   --prefix DIR   Install prefix (default: /usr/local). Also honours $PREFIX.
#   --uninstall    Remove the files this script installs.
#   --yes | -y     Skip the confirmation prompt.
#   --help | -h    Show this help.
#
# Icon-cache note: a freedesktop icon theme directory must contain an
# `index.theme`. When installing under a prefix that has no hicolor
# `index.theme` (typical for /usr/local), this script writes a minimal valid
# one so `gtk-update-icon-cache` succeeds instead of failing with an
# "index.theme not found" error. The generated index.theme carries a marker
# comment and is removed again on --uninstall (only if we created it).

set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────────

die()  { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN:  $*" >&2; }
info() { echo "  $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Argument parsing ──────────────────────────────────────────────────────────

MODE="install"
YES=false
PREFIX="${PREFIX:-/usr/local}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --uninstall) MODE="uninstall" ;;
        --prefix)    shift; [[ $# -gt 0 ]] || die "--prefix needs a directory"; PREFIX="$1" ;;
        --prefix=*)  PREFIX="${1#--prefix=}" ;;
        --yes|-y)    YES=true ;;
        --help|-h)
            sed -n '2,/^set -/p' "${BASH_SOURCE[0]}" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        *) die "Unknown argument: $1. Run with --help for usage." ;;
    esac
    shift
done

# ── Install destinations (derived from PREFIX) ────────────────────────────────

DEST_BIN="$PREFIX/bin/lattice"
DEST_DESKTOP="$PREFIX/share/applications/com.lattice.filemanager.desktop"
DEST_APPICON="$PREFIX/share/lattice/icons/lattice-icon.png"
HICOLOR_DIR="$PREFIX/share/icons/hicolor"
DEST_HICOLOR_ICON="$HICOLOR_DIR/256x256/apps/lattice.png"
DEST_INDEX_THEME="$HICOLOR_DIR/index.theme"
DEST_THEME_DEFAULT="$PREFIX/share/lattice/themes/default.css"
DEST_THEME_HIGH_CONTRAST="$PREFIX/share/lattice/themes/high-contrast.css"

INDEX_THEME_MARKER="# Generated by install-system.sh for the Lattice icon"

# ── Refresh helpers (never fail the run; report honestly) ─────────────────────

refresh_desktop_db() {
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$PREFIX/share/applications" \
            && info "✓ update-desktop-database $PREFIX/share/applications" \
            || warn "update-desktop-database reported an error"
    else
        warn "update-desktop-database not found (install desktop-file-utils) — desktop metadata not refreshed"
    fi
}

# Ensure the hicolor theme dir has a valid index.theme, then refresh the cache.
# We do NOT silence gtk-update-icon-cache errors: we remove their cause first.
refresh_icon_cache() {
    if [[ ! -f "$DEST_INDEX_THEME" ]]; then
        cat > "$DEST_INDEX_THEME" <<EOF
$INDEX_THEME_MARKER
[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true
Directories=256x256/apps

[256x256/apps]
Size=256
Context=Applications
Type=Fixed
EOF
        info "✓ wrote minimal valid $DEST_INDEX_THEME"
    fi

    # The command is named gtk-update-icon-cache on most distros and
    # gtk4-update-icon-cache on some GTK4-only layouts. Use the first found;
    # both accept the same `-f -t <themedir>` options.
    local _icon_cache_cmd=""
    for _c in gtk-update-icon-cache gtk4-update-icon-cache; do
        if command -v "$_c" >/dev/null 2>&1; then
            _icon_cache_cmd="$_c"
            break
        fi
    done

    if [[ -n "$_icon_cache_cmd" ]]; then
        "$_icon_cache_cmd" -f -t "$HICOLOR_DIR" \
            && info "✓ $_icon_cache_cmd $HICOLOR_DIR" \
            || warn "$_icon_cache_cmd reported an error for $HICOLOR_DIR"
    else
        warn "No icon-cache tool found (gtk-update-icon-cache / gtk4-update-icon-cache)."
        warn "The icon is still discoverable via runtime scan. Install one for faster startup:"
        warn "    Ubuntu: sudo apt install gtk-update-icon-cache"
        warn "    Arch:   sudo pacman -S gtk-update-icon-cache"
        warn "    Fedora: sudo dnf install gtk-update-icon-cache"
        warn "    Void:   sudo xbps-install gtk-update-icon-cache"
    fi
}

# ── Mode: install ─────────────────────────────────────────────────────────────

do_install() {
    [[ $EUID -eq 0 ]] || die "System install requires root. Run: sudo $0"

    local REL="$SOURCE_ROOT/target/release"
    [[ -f "$REL/lattice" ]] \
        || die "Release binary not found: $REL/lattice
Build it first with: cargo build --release"

    echo ""
    echo "Installing Lattice into prefix: $PREFIX"
    echo "This installs only Lattice's own files and does not touch user data."
    echo ""
    if [[ "$YES" != "true" ]]; then
        read -r -p "Continue? [y/N] " answer
        [[ "$answer" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
    fi

    install -Dm 755 "$REL/lattice" "$DEST_BIN"
    info "✓ $DEST_BIN"

    install -Dm 644 "$SOURCE_ROOT/com.lattice.filemanager.desktop" "$DEST_DESKTOP"
    info "✓ $DEST_DESKTOP"

    install -Dm 644 "$SOURCE_ROOT/icons/lattice-icon.png" "$DEST_APPICON"
    info "✓ $DEST_APPICON"

    install -Dm 644 "$SOURCE_ROOT/icons/lattice.png" "$DEST_HICOLOR_ICON"
    info "✓ $DEST_HICOLOR_ICON"

    install -Dm 644 "$SOURCE_ROOT/themes/default.css" "$DEST_THEME_DEFAULT"
    info "✓ $DEST_THEME_DEFAULT"

    install -Dm 644 "$SOURCE_ROOT/themes/high-contrast.css" "$DEST_THEME_HIGH_CONTRAST"
    info "✓ $DEST_THEME_HIGH_CONTRAST"

    echo ""
    echo "Refreshing desktop metadata and icon cache..."
    refresh_desktop_db
    refresh_icon_cache

    echo ""
    echo "Lattice installed."
    echo "  Launch:  $DEST_BIN   (ensure $PREFIX/bin is in PATH)"
    echo "  Verify:  command -v lattice"
    echo ""
    echo "To set Lattice as the default folder opener (explicit, optional):"
    echo "  xdg-mime default com.lattice.filemanager.desktop inode/directory"
    echo ""
    echo "Uninstall with: sudo $0 --uninstall --prefix $PREFIX"
}

# ── Mode: uninstall ───────────────────────────────────────────────────────────

do_uninstall() {
    [[ $EUID -eq 0 ]] || die "System uninstall requires root. Run: sudo $0 --uninstall"

    echo "Removing Lattice files from prefix: $PREFIX"
    echo ""

    local removed=0
    for f in \
        "$DEST_BIN" \
        "$DEST_DESKTOP" \
        "$DEST_APPICON" \
        "$DEST_HICOLOR_ICON" \
        "$DEST_THEME_DEFAULT" \
        "$DEST_THEME_HIGH_CONTRAST"; do
        if [[ -e "$f" ]]; then
            rm -f "$f"
            info "✓ removed $f"
            removed=$((removed + 1))
        else
            info "  (not found) $f"
        fi
    done

    # Remove index.theme only if we created it (marker present) — never remove a
    # distro-provided one.
    if [[ -f "$DEST_INDEX_THEME" ]] && grep -q "$INDEX_THEME_MARKER" "$DEST_INDEX_THEME" 2>/dev/null; then
        rm -f "$DEST_INDEX_THEME"
        info "✓ removed $DEST_INDEX_THEME (was generated by this script)"
    fi

    # Prune now-empty Lattice-owned directories (never prune shared system dirs).
    for d in \
        "$PREFIX/share/lattice/icons" \
        "$PREFIX/share/lattice/themes" \
        "$PREFIX/share/lattice"; do
        [[ -d "$d" ]] && rmdir "$d" 2>/dev/null && info "✓ removed empty $d" || true
    done

    echo ""
    echo "Refreshing desktop metadata and icon cache..."
    refresh_desktop_db
    if [[ -f "$DEST_INDEX_THEME" ]]; then
        for _c in gtk-update-icon-cache gtk4-update-icon-cache; do
            if command -v "$_c" >/dev/null 2>&1; then
                "$_c" -f -t "$HICOLOR_DIR" >/dev/null 2>&1 \
                    && info "✓ $_c $HICOLOR_DIR"
                break
            fi
        done
    fi

    echo ""
    if [[ $removed -gt 0 ]]; then
        echo "Lattice files removed. Your config, metadata, and cache were NOT touched:"
        echo "  ~/.config/lattice/  ~/.local/share/lattice/  ~/.cache/lattice/"
    else
        echo "No Lattice files found under $PREFIX — nothing removed."
    fi
}

# ── Dispatch ──────────────────────────────────────────────────────────────────

case "$MODE" in
    install)   do_install ;;
    uninstall) do_uninstall ;;
esac
